# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cfce589110d20b8d82ceabb7d5123e27b0d3ecec6a73856942d1a1fb7bfe2f69b4e6f2330e8e41ad903cddee02eb2c62244f75380e84ddf595d0d728c576cf9

test:
  secret_key_base: 57c0f7a2c9287371b2d33b5a358db74d5e2276fd51970d7889192c67c198604b4dc2595f547d640537b8db69d2de8ae542ad4ed74a1c6ac01061e0b5293e65cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
